---
# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "name.short" . | printf "%s-svcacc" | quote }}
  labels:
    app: {{ include "name.full" . | quote }}
imagePullSecrets:
  - name: {{ include "name.short" . | printf "%s-reg-auth" | quote }}
secrets:
  # SSH Server Private Key
  - name: {{ include "name.short" . | printf "%s-sshd-priv-key" | quote }}
---
# Registry Pull Secrets
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name.short" . | printf "%s-reg-auth" | quote }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "cntr.reg.auth" . }}