---
# SSH Server Private Key
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ include "name.full" . | quote }}
  name: {{ include "name.short" . | printf "%s-sshd-priv-key" | quote }}
type: kubernetes.io/ssh-auth
data:
  id_ed25519: {{ b64enc .Values.services.ssh.keyPair.priv }}
---
# SSH Server Public Key
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "name.full" . | quote }}
  name: {{ include "name.short" . | printf "%s-sshd-pub-key" | quote }}
data:
  id_ed25519.pub: |
{{ .Values.services.ssh.keyPair.pub | indent 4 }}
---
# SSH Server Config
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ include "name.full" . | quote }}
  name: {{ include "name.short" . | printf "%s-sshd-config" | quote }}
data:
  sshd_config: |
    # OpenSSH Server Config File
    LogLevel ERROR
    AuthorizedKeysFile %h/.ssh/authorized_keys
    CASignatureAlgorithms ssh-ed25519,sk-ssh-ed25519@openssh.com
    ClientAliveCountMax 5
    ClientAliveInterval 60
    Compression yes
    DenyGroups !vscode
    DisableForwarding yes
    HostKey {{ .Values.container.mounts.sshd }}/id_ed25519
    HostKeyAlgorithms ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,ssh-ed25519,sk-ssh-ed25519@openssh.com
    PasswordAuthentication no
    PermitEmptyPasswords no
    PermitRootLogin no
    PubkeyAuthentication yes
    PubkeyAcceptedKeyTypes ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,ssh-ed25519,sk-ssh-ed25519@openssh.com
    Subsystem sftp internal-sftp
---
# SSH Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "name.short" . | printf "%s-workspace-ssh-svc" | quote }}
  labels:
    app: {{ include "name.full" . | quote }}
spec:
  type: LoadBalancer
  selector:
    app: {{ include "name.full" . | quote }}
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: ssh
