### YAML Anchors ###

_k8s_provider:
  name: 
    full: &k8s_fname digital-ocean
    short: &k8s_sname do
  storageClass: &k8s_storageClass do-block-storage

### Start Values ###

workspace:
  # remote:
  #   ssh: "git@gitlab.com:pahansen95/eap-proxy.git"
  #   ref: main
  env: {}
  ssh:
    authorizedKeys: []
    config: |
      # SSH Client Config

      ### Global Config ###
      Compression yes
      PasswordAuthentication no
      PubkeyAuthentication yes
      UpdateHostKeys yes

      ### Hosts ###
      Host gitlab.com
        AddKeysToAgent yes
        IdentityFile ~/.ssh/gitlab.com
      Host github.com
        AddKeysToAgent yes
        IdentityFile ~/.ssh/github.com
    keys:
      "gitlab.com": ""
      "github.com": ""

container:
  mounts:
    workspace: /home/vscode/workspace
    sshd: /home/vscode/.sshd
  pvcs:
    workspace:
      size: 8Gi
      storageClass: *k8s_storageClass
  image:
    registry: registry.digitalocean.com
    path: d1144b94-0905-4b0d-8784-a56bbe41a51b/remote-workspace
    tag: latest
    username: ""
    password: ""
  resources:
    cpu: 4000m
    mem: 16Gi

services:
  ssh:
    keyPair:
      pub: ""
      priv: ""

# Optional Values

##Overrides the Name of the Installed release to this value
# name: