### YAML Anchors ###

# _k8s_provider:
#   name: 
#     full: &k8s_fname digital-ocean
#     short: &k8s_sname do
#   storageClass: &k8s_storageClass do-block-storage

### Start Values ###

workspace:
  # remote:
  #   ssh: "git@gitlab.com:pahansen95/eap-proxy.git"
  #   ref: main
  env: {}
  files:
    # Items in the lists take the form
    #
    # - dest: "/path/to/file.ext"
    #   data: |
    #     Literal Content of the file
    #
    secrets: []
    configMaps: []
  ssh:
    authorizedKeys: []
    config: 
      header: |
        # SSH Client Config
        Include ~/workspace/.ssh/user_config

        ### Global Config ###
        # Compression yes
        Compression no
        PasswordAuthentication no
        PubkeyAuthentication yes
        UpdateHostKeys yes
      hosts: 
        github.com:
          AddKeysToAgent: "yes"
          IdentityFile: "~/.ssh/github.com"
        gitlab.com:
          AddKeysToAgent: "yes"
          IdentityFile: "~/.ssh/gitlab.com"
    keys:
      github.com: ""
      gitlab.com: ""

container:
  mounts:
    workspace: /home/vscode/workspace
    sshd: /home/vscode/.sshd
  pvcs:
    workspace:
      size: 8Gi
      # storageClass: *k8s_storageClass
  image:
    registry: registry.home.peterhansen.io
    path: remote-workspace/workspace
    tag: latest
    username: ""
    password: ""
  resources:
    cpu: 4000m
    mem: 16Gi
    gpu: 
      nvidia: 0
      amd: 0

services:
  ssh:
    keyPair:
      pub: ""
      priv: ""

# Optional Values

##Overrides the Name of the Installed release to this value
# name: